#!/bin/sh

set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/bin/sudo /usr/bin/systemctl --quiet enable opendkim-autodiscovery.service
  /usr/bin/sudo /usr/bin/systemctl --quiet enable opendkim.service

  if test -f "enabled"; then
    echo "dkim is already enabled."
  elif test -f "disabled"; then
    mv "disabled" "enabled"
    /usr/bin/sudo /usr/bin/systemctl restart opendkim-autodiscovery.service
    /usr/bin/sudo /usr/bin/systemctl restart opendkim.service
  else
    touch "enabled"
    echo "dkim will be enabled on next reboot."
  fi

  if test -f "enabled"; then
    mkdir -p /etc/device/services/mail/smtp/milters
    ln -s /run/opendkim/opendkim.sock /etc/device/services/mail/smtp/milters/10-opendkim
  fi

fi

