#!/bin/sh

set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/libexec/device-set --remove domain --fqdn domain "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart opendkim-autodiscovery.service
  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart opendkim.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set --remove domain --fqdn domain "$@"

fi

