#!/bin/sh

set -e
umask 0002

OPTIONS="--remove domain --fqdn domain"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  if systemctl is-active --quiet opendkim-autodiscovery.service; then
    /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart opendkim-autodiscovery.service
    /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart opendkim.service
  else
    echo "dkim will be enabled on next reboot."
  fi

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

