#!/bin/sh

set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/libexec/device-set --set domain --fqdn domain --hostname selector --symlink-base=/etc/pki/tls/private --symlink-suffix=.pem --symlink=key "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart opendkim-autodiscovery.service
  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart opendkim.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set --set domain --fqdn domain --hostname selector --symlink-base=/etc/pki/tls/private --symlink-suffix=.pem --symlink=key "$@"

fi

