#!/bin/sh

set -e
umask 0002

OPTIONS="--show domain --show-table domain,selector,key --hostname selector --required --fqdn domain --symlink-base=/etc/pki/tls/private --symlink-suffix=.pem --symlink=key"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

